name: Build Windows EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.5'

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        cd details
        go mod tidy

    - name: Build EXE
      run: |
        cd details
        go build -o ./sudoku.exe main.go

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v2
      with:
        name: sudoku-exe
        path: details/sudoku.exe
