name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'  # Cette ligne permet de déclencher le workflow quand un tag est poussé (ex: v1.0.0)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    # Étape pour mettre en cache les dépendances Go
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        cd details
        go mod tidy

    - name: Build EXE
      run: |
        cd details
        go build -o ../sudoku.exe main.go

    # Étape pour uploader l'EXE en tant qu'asset de la release
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sudoku-exe
        path: ../sudoku.exe

    # Étape pour créer une release et y ajouter l'EXE
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ../sudoku.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
